schema_version = "1.0.0"
id = "sciblend"
version = "1.1.0"
name = "SciBlend"
tagline = "Scientific visualization tools for Blender"
type = "add-on"
maintainer = "José Marín"
blender_version_min = "4.5.1"
license = ["SPDX:GPL-3.0-or-later"]
description = """
v.4.0.0

This addon enhances Blender's capabilities with specialized tools for importing and managing scientific data formats. Key features include:

- Import and visualization of VTK, VTU, PVTU files
- Import and visualization of NetCDF files with support for:
  * Time-series data
  * Spherical projections for global/planetary data
  * Automatic attribute handling
- Import and visualization of Shapefiles (.shp) with:
  * DBF attribute support
  * Automatic extrusion options
  * Scale control
  * Delaunay triangulation for terrain modeling
  * Advanced point cloud processing
- Import and management of X3D files and scenes
- Group objects by type (cameras, lights, meshes)
- Quick scene setup with predefined lighting and render settings
- Streamlined UI panel for easy access to all functions
"""

platforms = ["windows-x64", "linux-x64", "macos-x64", "macos-arm64"]

# Wheels
wheels = [
  # platform-independent
  "./wheels/common/attrs-25.3.0-py3-none-any.whl",
  "./wheels/common/certifi-2025.8.3-py3-none-any.whl",
  "./wheels/common/click-8.2.1-py3-none-any.whl",
  "./wheels/common/click_plugins-1.1.1.2-py2.py3-none-any.whl",
  "./wheels/common/cligj-0.7.2-py3-none-any.whl",
  "./wheels/common/cycler-0.12.1-py3-none-any.whl",
  "./wheels/common/geopandas-1.0.1-py3-none-any.whl",
  "./wheels/common/importlib_metadata-8.7.0-py3-none-any.whl",
  "./wheels/common/packaging-25.0-py3-none-any.whl",
  "./wheels/common/pyparsing-3.2.3-py3-none-any.whl",
  "./wheels/common/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
  "./wheels/common/pytz-2025.2-py2.py3-none-any.whl",
  "./wheels/common/six-1.17.0-py2.py3-none-any.whl",
  "./wheels/common/typing_extensions-4.14.1-py3-none-any.whl",
  "./wheels/common/tzdata-2025.2-py2.py3-none-any.whl",
  "./wheels/common/zipp-3.23.0-py3-none-any.whl",

  # windows-x64
  "./wheels/windows-x64/cftime-1.6.4.post1-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/contourpy-1.3.3-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/fiona-1.9.6-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/fonttools-4.59.1-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/kiwisolver-1.4.9-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/matplotlib-3.10.5-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/netCDF4-1.7.2-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/pandas-2.2.3-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/pillow-11.3.0-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/pyogrio-0.11.1-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/pyproj-3.6.1-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/shapely-2.0.6-cp311-cp311-win_amd64.whl",
  "./wheels/windows-x64/vtk-9.3.0-cp311-cp311-win_amd64.whl",

  # linux-x64
  "./wheels/linux-x64/cftime-1.6.4.post1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/linux-x64/contourpy-1.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/linux-x64/fiona-1.9.6-cp311-cp311-manylinux2014_x86_64.whl",
  "./wheels/linux-x64/fonttools-4.59.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/linux-x64/kiwisolver-1.4.9-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/linux-x64/matplotlib-3.10.5-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/linux-x64/netCDF4-1.7.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/linux-x64/pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/linux-x64/pillow-11.3.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/linux-x64/pyogrio-0.11.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/linux-x64/pyproj-3.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/linux-x64/shapely-2.0.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/linux-x64/vtk-9.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",

  # macos-x64
  "./wheels/macos-x64/cftime-1.6.4.post1-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/macos-x64/contourpy-1.3.3-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/macos-x64/fiona-1.9.6-cp311-cp311-macosx_10_15_x86_64.whl",
  "./wheels/macos-x64/fonttools-4.59.1-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/macos-x64/kiwisolver-1.4.9-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/macos-x64/matplotlib-3.10.5-cp311-cp311-macosx_10_12_x86_64.whl",
  "./wheels/macos-x64/netCDF4-1.6.5-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/macos-x64/pandas-2.2.3-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/macos-x64/pillow-11.3.0-cp311-cp311-macosx_10_10_x86_64.whl",
  "./wheels/macos-x64/pyogrio-0.8.0-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/macos-x64/pyproj-3.6.1-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/macos-x64/shapely-2.0.6-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/macos-x64/vtk-9.3.0-cp311-cp311-macosx_10_10_x86_64.whl",

  # macos-arm64
  "./wheels/macos-arm64/cftime-1.6.4.post1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/fiona-1.9.6-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/kiwisolver-1.4.9-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/matplotlib-3.10.5-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/netCDF4-1.6.5-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/pandas-2.2.3-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/pillow-11.3.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/pyogrio-0.8.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/pyproj-3.6.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/shapely-2.0.6-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/macos-arm64/vtk-9.3.0-cp311-cp311-macosx_11_0_arm64.whl",
]
