name: Build SciBlend Extension

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
    paths:
      - 'blender_manifest.toml'
      - 'SciBlend/**'
      - 'scripts/**'
      - '.github/workflows/build-extension.yml'
  pull_request:
    branches: [ main, master ]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ linux-x64, windows-x64, macos-x64, macos-arm64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Prepare wheels
        run: |
          mkdir -p wheels
          chmod +x scripts/fetch_wheels.sh || true
          ./scripts/fetch_wheels.sh

      - name: Build platform zip (no Blender)
        run: |
          python scripts/make_extension_zip.py --target "${{ matrix.target }}" --outdir dist
          ls -lh dist

      - name: Upload artifact (${{ matrix.target }})
        uses: actions/upload-artifact@v4
        with:
          name: sciblend-extension-${{ matrix.target }}
          path: dist/*-${{ matrix.target }}.zip 