name: Build SciBlend Extension

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
    paths:
      - 'blender_manifest.toml'
      - 'SciBlend/**'
      - 'constraints/**'
      - 'scripts/**'
      - '.github/workflows/build-extension.yml'
  pull_request:
    branches: [ main, master ]

jobs:
  build-all-platforms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Fetch platform wheels
        run: |
          set -euo pipefail
          chmod +x scripts/fetch_wheels.sh
          ./scripts/fetch_wheels.sh

      - name: Consolidate wheels into root wheels/
        run: |
          set -euo pipefail
          mkdir -p wheels
          for d in wheels/linux-x64 wheels/windows-x64 wheels/macos-x64 wheels/macos-arm64 wheels/common; do
            if [ -d "$d" ]; then
              shopt -s nullglob
              mv -f "$d"/*.whl wheels/ || true
              shopt -u nullglob
            fi
          done
          ls -lh wheels || true

      - name: Download Blender 4.5.1
        run: |
          set -euo pipefail
          BLENDER_VERSION=4.5.1
          BASE_URL=https://download.blender.org/release/Blender4.5
          FILE=blender-${BLENDER_VERSION}-linux-x64.tar.xz
          curl -L -o "$RUNNER_TEMP/$FILE" "$BASE_URL/$FILE"
          tar -C "$RUNNER_TEMP" -xf "$RUNNER_TEMP/$FILE"
          echo "BLENDER_BIN=$(find "$RUNNER_TEMP" -type f -name blender -path '*linux-x64/*' | head -n1)" >> "$GITHUB_ENV"

      - name: Clean workspace before Blender build
        run: |
          set -euo pipefail
          rm -rf "Paraview Macros" constraints images scripts .github README.md .gitignore || true

      - name: Build extension (split-platforms)
        run: |
          set -euo pipefail
          mkdir -p dist
          "$BLENDER_BIN" --command extension build --source-dir . --output-dir dist --split-platforms
          ls -lh dist

      - name: Upload artifact (linux-x64)
        uses: actions/upload-artifact@v4
        with:
          name: sciblend-linux-x64
          path: dist/*linux*.zip
          if-no-files-found: ignore

      - name: Upload artifact (windows-x64)
        uses: actions/upload-artifact@v4
        with:
          name: sciblend-windows-x64
          path: dist/*windows*.zip
          if-no-files-found: ignore

      - name: Upload artifact (macos-x64)
        uses: actions/upload-artifact@v4
        with:
          name: sciblend-macos-x64
          path: dist/*macos-x64*.zip
          if-no-files-found: ignore

      - name: Upload artifact (macos-arm64)
        uses: actions/upload-artifact@v4
        with:
          name: sciblend-macos-arm64
          path: dist/*macos-arm64*.zip
          if-no-files-found: ignore