name: Build SciBlend Extension

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
    paths:
      - 'blender_manifest.toml'
      - 'SciBlend/**'
      - 'constraints/**'
      - 'scripts/**'
      - '.github/workflows/build-extension.yml'
  pull_request:
    branches: [ main, master ]

jobs:
  build-all-platforms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Prepare wheels (platform directories)
        run: |
          chmod +x scripts/fetch_wheels.sh
          ./scripts/fetch_wheels.sh

      - name: Build split zips (no Blender)
        run: |
          mkdir -p dist
          python scripts/make_extension_zip.py --target linux-x64   --outdir dist
          python scripts/make_extension_zip.py --target windows-x64 --outdir dist
          python scripts/make_extension_zip.py --target macos-x64   --outdir dist
          python scripts/make_extension_zip.py --target macos-arm64 --outdir dist
          ls -lh dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sciblend-extension-split
          path: dist/*.zip